### ISSUE TITLE
[false positive] "These two nested ifs can be merged into one" when using if + macro + inline

### ISSUE THREAD

**Issue by mauhiz** [HairyFotr/linter#18]
Say we have a macro for debugging:

`@inline def debug(msg: => String): Unit = macro debugImpl`

with debugImpl being equivalent to:

`if (Logger.isDebugEnabled) Logger.debug(msg)`

Then errors are reported on the call sites of this method:

`if (someCondition) debug(msg)` <<<

**Comment by HairyFotr** [comment]
I'm guessing it could be that it's not because it's a macro, but because of the @inline.

I'll take a closer look later today.

**Comment by HairyFotr** [comment]
I've published the fix under 0.1-SNAPSHOT (as usual), so just run sbt update, and compile normally, and hopefully this false positive is fixed.

**Comment by mauhiz** [comment]
@HairyFotr amazing! thanks

**Comment by HairyFotr** [comment]
Thank you for reporting it!
