### ISSUE TITLE
too slow..

### ISSUE THREAD

**Issue by OlegYch** [HairyFotr/linter#20]
the plugin impacts compilation time quite severely
for me it goes up from about 300 secs to about 600
even enabling just one check, eg enable-only:UnlikelyEquality still gives me about 600 secs

**Comment by HairyFotr** [comment]
Thanks for measuring and reporting - I haven't done it in a while, but it used to be around ~15-20%, but it had one compiler phase fewer, and the abstract interpreter was not as big as it is now (I suspect most of the time is spent here).

Right now the whole analysis runs, regardless of enabled/disabled checks, so there's obviously a lot of room for optimisation - I hope to find the energy to work on that on sunday.

**Comment by HairyFotr** [comment]
Merging issue with #39

**Comment by fsvehla** [comment]
Is it possible to run Linter not on every compile - maybe define a `sbt lint` command?

**Comment by HairyFotr** [comment]
It's not done in Linter itself (I would have to make an extra sbt plugin - I'll get around to that someday :)), but there is an [example of doing this in your sbt config here](https://github.com/leifwickland/static-analysis-skeleton).
