### ISSUE TITLE
Publish on maven central/sonatype

### ISSUE THREAD

**Issue by TimSoethout** [HairyFotr/linter#22]
Thanks for your Linter!
Is it possible to have it published on a more default repository such as Maven Central? This way it will be possible to get it into our corporate Nexus.

**Comment by HairyFotr** [comment]
One issue is the foursquare package name that I kept from the original repo - I'll rename the package before publishing to a more public repository, since I'm not connected to them in any way. Other than that, yes, I think it's about time I publish it properly. Thanks!

**Comment by TimSoethout** [comment]
Cheers. If I can help with anything please let me know.
I recently published a maven plugin using Sonatype OSS hosting. This guide turned out to be easy to follow: http://central.sonatype.org/pages/ossrh-guide.html

**Comment by HairyFotr** [comment]
I've renamed the package, made the changes needed (except the publishTo Sonatype) according to [this tutorial](http://www.scala-sbt.org/0.13/docs/Using-Sonatype.html), and filled a [ticket with Sonatype](https://issues.sonatype.org/browse/OSSRH-16774). I'll publish as soon as it's resolved.

**Comment by HairyFotr** [comment]
Version 0.1.12 has been published to Sonatype.
