### ISSUE TITLE
[warn] dropping dependency on node with no phase object: refchecks

### ISSUE THREAD

**Issue by zzztimbo** [HairyFotr/linter#23]
I get this error when I try to generate scaladocs: [warn] dropping dependency on node with no phase object: refchecks

```scala
sbt doc
```

**Comment by HairyFotr** [comment]
Interesting, scaladoc doesn't run the entire compilation process and so it doesn't hit the `refchecks` compiler phase (run `scalac -Xshow-phases` to see what I mean, but `scaladoc -Xshow-phases` just warns "Phases are restricted when using Scaladoc", but doesn't give a list). Linter adds its own compiler phase after `refchecks`, but the setting is just a plain string in the compiler plugin API - will have to check the docs if there's a way to list existing compiler phases before registering linter's compiler phases.

It's a warning and I think it shouldn't be causing any problems beyond printing this, but I'll check and try to fix when I find time.

One workaround would also be to limit linter in sbt to only the tasks where it's needed (I think in Compile and if you lint tests, in Test), but I don't know enough about that sbt feature to write the config: http://www.scala-sbt.org/0.13.5/docs/Detailed-Topics/Tasks.html

**Comment by coltfred** [comment]
@HairyFotr It's a warning, but if you have `"-Xfatal-warnings"` turned on, it breaks the build. I hope a majority of people have that turned on so it's probably a bigger deal than it seems.

**Comment by HairyFotr** [comment]
You're right, and knowing this does raise the priority of the issue. The fix will need to be disabling parts or maybe even the whole Linter if the required compiler phases are not available, so I think I'll still output something (but more informative than what the compiler spits out). And it will be `info`, not `warn`, so it will not break the build on `-Xfatal-warnings`.

**Comment by coltfred** [comment]
@HairyFotr An info log would be great! Thanks for your attention to the issue!

**Comment by ckozak** [comment]
@HairyFotr did you have a chance to look at this issue?

**Comment by TomasMikula** [comment]
Glad to see this has been fixed! Is there any estimate for when this gets released?

**Comment by HairyFotr** [comment]
I'd like to solve a few more issues, and I left my release signing keys at home... so, ~2 weeks

**Comment by TomasMikula** [comment]
I, too, hate it when I leave my keys at home! 😉 
Thanks for the estimate!
