### ISSUE TITLE
jenkins/sonar/report integration, error/warning 

### ISSUE THREAD

**Issue by kknd22** [HairyFotr/linter#32]
is there some mechanism to integrate the finding result with sonar/jenkins or any other reporting mechenism?

Moreover, can it be configured to stop the build for any or some warning/error?
Thanks

-Chris L.

**Comment by jvstein** [comment]
The Jenkins [Warnings Plug-in](https://wiki.jenkins-ci.org/display/JENKINS/Warnings+Plugin) has the ability to pick up scala compiler warnings.

For stopping the build, scalac has the `-Xfatal-warnings` flag, which can be enabled using your build tool. It looks like it's easy to configure in both maven and sbt.

**Comment by HairyFotr** [comment]
Thanks for answering, closing.
