### ISSUE TITLE
ContainsTypeMismatch doesn't seem to be working

### ISSUE THREAD

**Issue by levinson** [HairyFotr/linter#45]
I am using SBT 0.13.11, Scala 2.11.8 and 0.1.14 version of the compiler plugin, and the ContainsTypeMismatch check does not catch any of the following:
`Some("foo").contains(1)`
`Some(1).contains("foo")`
`List(4).contains("foo")`

I haven't found a case where it is working properly. The UnlikelyEquality check is working fine, so I don't believe it's an issue with my build.

**Comment by HairyFotr** [comment]
Thanks for reporting! 0.1-SNAPSHOT is updated, 0.1.15 comes after I fix a few more bugs.

**Comment by levinson** [comment]
Thanks for the quick turnaround!
